### ISSUE TITLE
Better feedback for incorrect data entry

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-react-form#77]
Current behaviour :
If i enter a letters in a number question , on moving focus it blanks out the response without informing the user that they have entered an invalid value and that it was not registered

Expected:
We should show an error to the user (by highlighting the question with errors ) and ask them to fix it

Testcases
Enter text in number field . Error Message "Only number allowed"
Enter a decimal in questions which does not have allow decimal enabled .Error Message "Only integers allowed"

**Comment by navins94** [comment]
@joycarpediem I have restricted user from entering letters in input number

**Comment by dedenbangkit** [comment]
Add Icon before the fields https://react-icons.github.io/react-icons/

**Comment by navins94** [comment]
I am not able to find appropriate icon to indicate if the field is number. Could you please suggest something similar

**Comment by navins94** [comment]
@dedenbangkit @joycarpediem @wayangalihpratama 
Let me know if this works or not 
![Screenshot 2023-02-14 at 4 02 13 PM](https://user-images.githubusercontent.com/24510012/218710111-fd963d92-667c-4d18-a5c8-360d004c414d.png)
![Screenshot 2023-02-14 at 4 02 23 PM](https://user-images.githubusercontent.com/24510012/218710161-86ea362b-821b-4e2e-951b-ae0b4a2b2a9b.png)

**Comment by wayangalihpratama** [comment]
Hi @navins94 , 
for me, the icon does not describe that field's input type. 
Also, the icon placement looks weird when we have a number type of question like a phone number.
![Screenshot from 2023-02-16 09-32-56](https://user-images.githubusercontent.com/49269977/219240758-c18418f3-43c5-4ec7-924b-eeed912da6bd.png)

**Comment by navins94** [comment]
@wayangalihpratama I got those icons from one of the components only where we are using it to represent number field

**Comment by joycarpediem** [comment]
@navins94 , a couple of things 
1. I was thinking about placing the icon as a prefix to the question <icon> <question number > <question text>

2. The icons need to be a bit more explicit . So for number , something like [123]

**Comment by navins94** [comment]
Does anyone know where to look for those as I was not able to find in react-icons

**Comment by navins94** [comment]
How about this ?
![Screenshot 2023-02-18 at 12 01 23 AM](https://user-images.githubusercontent.com/24510012/219752742-14edb663-e33f-45da-a24d-50f92151f626.png)
