### ISSUE TITLE
Replace Core Mandatory with Required Symbol

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/akvo-react-form#91]
- `coreMandatory` is a specific project-related parameters. If we are going to have this as main feature of Akvo React Form, we should  give more context why we have this parameter in the description and what is the example case.
- or: Instead of coreMandatory, `customMandatorySign` parameter is more understandable.

**Comment by joycarpediem** [comment]
I agree. A feature like coreMandatory and the effect on react form should be as minimal and generic as possible

**Comment by dedenbangkit** [comment]
- [ ] Remove `coreMandatory` and replace it with `requiredSign`, string / react component. In documentation, default "*".
- [ ] Required documentation is missing
